name: "Flutter Temporary Release"

on:
  push:
    branches:
      - main
  workflow_dispatch: # allow manual trigger

jobs:
  build-android:
    name: Build & Release Android
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v3

      # Step 2: Setup Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Build APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      # Step 6: Build AAB
      - name: Build AAB
        run: flutter build appbundle --release

      # Step 7: Upload to GitHub Release
      - name: Publish to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*.apk
            build/app/outputs/bundle/release/*.aab
          tag: temp-${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
